server:
  port: 8088

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/treta-bot
      readPreference: 'secondaryPreferred'
      writeConcern: 'W1'

bot:
  token: "ODI1MTE1MDQ1ODg0NzIzMjAw.YF5ORA.sNULh7u62OHbHflj1TfEwm_1SPA"