server:
  port: 8088

logging:
  level:
    root: WARN
    org.springframework.boot.web.embedded.undertow.UndertowWebServer: INFO
    br.com: INFO

bot:
  prefix: "$"
  token: "ODI1MTE1MDQ1ODg0NzIzMjAw.YF5ORA.sNULh7u62OHbHflj1TfEwm_1SPA"